/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MemeGenerator {
  constructor(options?: InitOptions | undefined | null)
  version(): string
  memeHome(): string
  stateDbPath(): string
  readConfigFile(): string
  getMemeKeys(includeDisabled?: boolean | undefined | null): Array<string>
  getMemeInfo(key: string): MemeInfoDto | null
  getMemesInfo(includeDisabled?: boolean | undefined | null): Array<MemeInfoDto>
  searchMemes(query: string, includeTags?: boolean | undefined | null, includeDisabled?: boolean | undefined | null): Array<string>
  setMemeEnabled(key: string, enabled: boolean): void
  isMemeEnabled(key: string): boolean
  listMemeStates(): Array<MemeState>
  getDisabledMemeKeys(): Array<string>
  generateMeme(payload: GenerateMemePayload): Buffer
  generateMemePreview(key: string, options?: any | undefined | null): Buffer
  generateMemeDetailed(payload: GenerateMemePayload): GenerateMemeResult
  validateGeneratePayload(payload: GenerateMemePayload): GenerateValidationResult
  checkResources(baseUrl?: string | undefined | null): void
  checkResourcesInBackground(baseUrl?: string | undefined | null): void
  inspectImage(image: Buffer): any
  flipHorizontal(image: Buffer): Buffer
  flipVertical(image: Buffer): Buffer
  rotate(image: Buffer, degrees?: number | undefined | null): Buffer
  resize(image: Buffer, width?: number | undefined | null, height?: number | undefined | null): Buffer
  crop(image: Buffer, left?: number | undefined | null, top?: number | undefined | null, right?: number | undefined | null, bottom?: number | undefined | null): Buffer
  grayscale(image: Buffer): Buffer
  invert(image: Buffer): Buffer
  mergeHorizontal(images: Array<Buffer>): Buffer
  mergeVertical(images: Array<Buffer>): Buffer
  gifSplit(image: Buffer): Array<Buffer>
  gifMerge(images: Array<Buffer>, duration?: number | undefined | null): Buffer
  gifReverse(image: Buffer): Buffer
  gifChangeDuration(image: Buffer, duration: number): Buffer
  renderMemeList(params?: any | undefined | null): Buffer
  renderMemeStatistics(params: any): Buffer
  getResourceStatus(key?: string | undefined | null): Array<ResourceStatus>
  generateRandom(payload?: GenerateRandomPayload | undefined | null): GenerateMemeResult
}

export interface GenerateMemePayload {
  key: string
  images?: Array<InputImagePayload>
  texts?: Array<string>
  options?: any
}

export interface GenerateMemeResult {
  key: string
  buffer: Buffer
  mime: string
  usedImages: number
  usedTexts: number
}

export interface GenerateRandomPayload {
  filters?: RandomGenerateFilter
  images?: Array<InputImagePayload>
  texts?: Array<string>
  options?: any
}

export interface GenerateValidationResult {
  ok: boolean
  issues: Array<ValidationIssue>
  requiredMinImages: number
  requiredMaxImages: number
  requiredMinTexts: number
  requiredMaxTexts: number
}

export interface InitOptions {
  dbPath?: string
  maxTextLength?: number
}

export interface InputImagePayload {
  name?: string
  data: Buffer
}

export interface MemeInfoDto {
  key: string
  params: MemeParamsDto
  keywords: Array<string>
  shortcuts: Array<MemeShortcutDto>
  tags: Array<string>
  dateCreated: string
  dateModified: string
  enabled: boolean
}

export interface MemeOptionDto {
  optionType: string
  name: string
  description?: string
  parserFlags: ParserFlagsDto
  defaultValue?: any
  choices?: Array<string>
  minimum?: number
  maximum?: number
}

export interface MemeParamsDto {
  minImages: number
  maxImages: number
  minTexts: number
  maxTexts: number
  defaultTexts: Array<string>
  options: Array<MemeOptionDto>
}

export interface MemeShortcutDto {
  pattern: string
  humanized?: string
  names: Array<string>
  texts: Array<string>
  options: any
}

export interface MemeState {
  key: string
  enabled: boolean
}

export interface ParserFlagsDto {
  short: boolean
  long: boolean
  shortAliases: Array<string>
  longAliases: Array<string>
}

export interface RandomGenerateFilter {
  requireImages?: boolean
  minTexts?: number
  maxTexts?: number
  excludeKeys?: Array<string>
  includeDisabled?: boolean
}

export interface ResourceStatus {
  key: string
  enabled: boolean
  available: boolean
  code?: string
  message?: string
}

export interface ValidationIssue {
  code: string
  field: string
  message: string
}
